### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by SousaSoftware** [Eli45/CSGOBindGen#1]
Value generated in Output is for example [ bind "kp_end" "buy p250";] and should be [ bind "kp_end" "buy p250;"]

; is placed after ", but for CSGO cfg it should be after "

Fixed Code http://pastebin.com/BGRnJbDL

Anyway really good work

Since i fixed the code it works, well

Do you pretend to update and give multiweapon to one bind?
You can do that easily, example  [ bind "kp_end" "buy p250; buy flashbang; buy smokegrenade;"] 

Greetings
SousaSoft

**Comment by Eli45** [comment]
This is an older version of my bind generator that I decided to keep up simply because it's so different that the new version found [here](https://github.com/Eli45/csgo_new_bind_gen). The new version supports having multiple weapons bound to a single key along with multiple grenades. In the updated version the issue you're describing is fixed and allows multiple weapons to one key and is all around better.
